{% set name = "braq" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/braq-{{ version }}.tar.gz
  sha256: 07f83a262339d19f649c08b3a0e047591a5d50362f7e9dc06a24210bbeabcb5d

build:
  entry_points:
    - braq = braq.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.5
    - written

test:
  imports:
    - braq
  commands:
    - pip check
    - braq --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/braq
  summary: The most obvious way to section a document
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
