{% set name = "braq" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/braq-{{ version }}.tar.gz
  sha256: 5a48450bca1486a3c1f76d96d8a22b1c4e066f0fbf3a583fdae8a0bf8a2b310b

build:
  entry_points:
    - braq = braq.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.5
    - paradict
    - written

test:
  imports:
    - braq
  commands:
    - pip check
    - braq --help
  requires:
    - pip

about:
  home: https://github.com/pyrustic/braq
  summary: The most obvious way to section a document
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
