{% set name = "braq" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/braq-{{ version }}.tar.gz
  sha256: 51dae51b863cbba2cd37da163df06b7dc5124904d2c26b92bda54c1bde66d74b

build:
  entry_points:
    - braq = braq.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - braq
  commands:
    - pip check
    - braq --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/braq
  summary: The most obvious way to section a document
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
