{% set name = "braq" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/braq-{{ version }}.tar.gz
  sha256: 02c782d538558833f630adcd7ec56a150efb2fe6b45e49d48922d4d2dcbe888c

build:
  entry_points:
    - braq = braq.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - paradict
    - written

test:
  imports:
    - braq
  commands:
    - pip check
    - braq --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyrustic/braq
  summary: The most obvious way to section a document
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
